import { IthakaFormFieldMetadata } from "./interfaces/IthakaFormFieldMetadata";

export const ithakaFormSchema: IthakaFormFieldMetadata[] = [
  {
    field: "name",
    label: "Nombre",
    description: "Primer nombre del emprendedor.",
    section: "Datos Personales",
    type: "string",
    importance: "critical",
  },
  {
    field: "lastname",
    label: "Apellido",
    description: "Apellido del emprendedor.",
    section: "Datos Personales",
    type: "string",
    importance: "critical",
  },
  {
    field: "email",
    label: "Correo electrónico",
    description: "Dirección de correo electrónico del emprendedor.",
    section: "Datos Personales",
    type: "string",
    importance: "critical",
  },
  {
    field: "cellphone",
    label: "Celular o teléfono",
    description: "Número de teléfono o celular de contacto.",
    section: "Datos Personales",
    type: "string",
    importance: "critical",
  },
  {
    field: "ci",
    label: "Cédula de Identidad",
    description: "Número de cédula de identidad uruguaya.",
    section: "Datos Personales",
    type: "string",
    importance: "critical",
  },
  {
    field: "placeOfResidence",
    label: "Departamento de residencia",
    description: "Departamento donde reside el emprendedor.",
    section: "Datos Personales",
    type: "select",
    importance: "critical",
    aiExtractionHints: ["vivo en", "resido en", "mi ciudad es"],
  },
  {
    field: "placeOfContactIthaka",
    label: "Departamento de contacto con Ithaka",
    description: "Departamento en el que preferiría ser contactado por Ithaka.",
    section: "Datos Personales",
    type: "select",
    importance: "optional",
    aiExtractionHints: ["prefiero contactarme en", "me gustaría que me contacten en"],
  },
  {
    field: "relationToUCU",
    label: "Relación con la UCU",
    description: "Tipo de relación actual con la Universidad Católica del Uruguay (Estudiante, Docente, Egresado, Ninguna).",
    section: "Relación con la UCU",
    type: "string",
    importance: "critical",
    aiExtractionHints: ["soy estudiante de", "soy docente", "egresé de", "no tengo relación con la UCU"],
  },
  {
    field: "howFoundOut",
    label: "Cómo se enteró de Ithaka",
    description: "Indicar cómo conoció el emprendedor a Ithaka.",
    section: "Relación con la UCU",
    type: "multiselect",
    importance: "optional",
    aiExtractionHints: ["me enteré por", "vi en", "me recomendaron"],
  },
  {
    field: "hasTeam",
    label: "Tiene equipo",
    description: "Indicar si el emprendedor tiene un equipo de trabajo para su proyecto.",
    section: "Equipo",
    type: "boolean",
    importance: "critical",
    aiExtractionHints: ["trabajo con", "somos un equipo", "estoy solo"],
  },
  {
    field: "team",
    label: "Miembros del equipo",
    description: "Lista de integrantes del equipo, con sus datos de contacto y rol.",
    section: "Equipo",
    type: "array",
    importance: "optional",
    isRepeatable: true,
    aiExtractionHints: ["mi equipo está compuesto por", "trabajo con", "me acompaña"],
  },
  {
    field: "previousExperience",
    label: "Experiencia previa",
    description: "Experiencia previa del emprendedor realizando emprendimientos.",
    section: "Detalles del Proyecto",
    type: "string",
    importance: "optional",
    aiExtractionHints: ["ya emprendí", "hice un emprendimiento", "es mi primera vez emprendiendo", "trabaje como"],
  },
  {
    field: "problemToSolve",
    label: "Problema a resolver",
    description: "Problema concreto que el emprendimiento busca resolver.",
    section: "Detalles del Proyecto",
    type: "string",
    importance: "critical",
    aiExtractionHints: ["el problema es", "detectamos que", "queremos solucionar"],
    aiEnrichmentHints: [
      "El problema es especifico",
      "El problema afecta una masa considerable de personas",
      "El problema es suficiente como para que la gente quiera pagar por resolverlo"
    ]
  },
  {
    field: "proposedSolution",
    label: "Solución propuesta",
    description: "Solución o propuesta de valor que ofrece el emprendimiento.",
    section: "Detalles del Proyecto",
    type: "string",
    importance: "critical",
    aiExtractionHints: ["la solución es", "proponemos", "desarrollamos"],
    aiEnrichmentHints: [
      "Como solucion resuelve o asiste en atender el problema definido",
      "La solucion es realista o factible",
      "La solucion es vendible",
    ]
  },
  {
    field: "differentialFromCompetitors",
    label: "Diferencial frente a competidores",
    description: "Valor diferencial o ventaja competitiva frente a otros en el mercado.",
    section: "Detalles del Proyecto",
    type: "string",
    importance: "critical",
    aiExtractionHints: ["a diferencia de", "nuestro diferencial es", "nos destacamos por"],
    aiEnrichmentHints: [
      "Como resuelven hoy las personas este problema",
      "El diferencial es suficiente para diferenciarse de competidores",
      "El diferencial es relevante para quienes sufren este problema",
    ]
  },
  {
    field: "businessModel",
    label: "Modelo de negocio",
    description: "Cómo hará dinero el proyecto (modelo de ingresos).",
    section: "Detalles del Proyecto",
    type: "string",
    importance: "critical",
    aiExtractionHints: ["vendemos", "modelo de suscripción", "comisiones por", "licencia de uso"],
  },
  {
    field: "currentProjectPhase",
    label: "Etapa del proyecto",
    description: "Fase actual del proyecto/emprendimiento.",
    section: "Detalles del Proyecto",
    type: "select",
    importance: "critical",
    aiExtractionHints: ["es solo una idea", "vengo trabajando hace un tiempo", "ya tenemos ventas", "es un emprendimiento consolidado"],
  },
  {
    field: "wantsFromIthaka",
    label: "Necesidades desde Ithaka",
    description: "Qué tipo de apoyo espera recibir de Ithaka.",
    section: "Apoyo de Ithaka",
    type: "multiselect",
    importance: "critical",
    aiExtractionHints: ["necesito ayuda con", "me gustaría recibir", "busco apoyo en"],
  },
  {
    field: "availableTime",
    label: "Horarios disponibles",
    description: "Franja horaria en la que el emprendedor prefiere tener reuniones.",
    section: "Datos Personales",
    type: "array",
    importance: "optional",
    aiExtractionHints: ["prefiero reunirme en la mañana", "mejor a la tarde", "de noche me queda bien"],
  },
  {
    field: "comments",
    label: "Comentarios adicionales",
    description: "Cualquier dato adicional o comentario que el emprendedor desee agregar.",
    section: "Comentarios",
    type: "string",
    importance: "optional",
  },
];
