apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ithaka-frontend-hpa
  namespace: ithaka-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ithaka-frontend-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
