import type { Metadata } from "next";
import { CopilotKit } from "@copilotkit/react-core";
import "./globals.css";
import "@copilotkit/react-ui/styles.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <CopilotKit
          runtimeUrl={process.env.NEXT_PUBLIC_RUNTIME_URL || "http://localhost:3000/api/copilotkit"}
        >
          {children}
        </CopilotKit>
      </body>
    </html>
  );
}
