import type { Metadata } from "next";

import { CopilotKit } from "@copilotkit/react-core";
import "./globals.css";
import "@copilotkit/react-ui/styles.css";

import { ChatProvider } from "@/context/ChatContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <CopilotKit
          publicApiKey={process.env.COPILOT_API_KEY || ""}
          >
          <ChatProvider>
            {children}
          </ChatProvider>
        </CopilotKit>
      </body>
    </html>
  );
}
