name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: crretoxmas2024.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Set image tag (current date)
        id: vars
        run: echo "tag=$(date +%Y-%m-%d)" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        run: |
          docker build -t crretoxmas2024.azurecr.io/ithaka-frontend:${{ steps.vars.outputs.tag }} .
          docker push crretoxmas2024.azurecr.io/ithaka-frontend:${{ steps.vars.outputs.tag }}
