name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: crretoxmas2024.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Extract short commit SHA
        id: vars
        run: echo "TAG=$(date +%Y-%m-%d)-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            crretoxmas2024.azurecr.io/ithaka-frontend:latest
            crretoxmas2024.azurecr.io/ithaka-frontend:${{ env.TAG }}
          cache-from: type=registry,ref=crretoxmas2024.azurecr.io/ithaka-frontend:cache
          cache-to: type=registry,ref=crretoxmas2024.azurecr.io/ithaka-frontend:cache,mode=max
